### ISSUE TITLE
Netflix解锁检测不能正确识别策略组

### ISSUE THREAD

**Issue by Mosney** [Hyseen/Scripts#1]
![image](https://user-images.githubusercontent.com/22477230/140715212-e1b13627-235d-40cf-bdc4-a487ee6a9de4.png)

点击保存按钮后，从BoxJS的当前会话来看（如图所示）并没有保存“策略组名称”变量，脚本是怎么获取到Netflix的策略组的呢？从脚本运行结果来看也确实获取不到

**Comment by Hyseen** [comment]
1. 当前会话里面没有显示是因为我没有让它显示
2. 请确认 QuanX 里面配置了 Netflix 相关的策略组，并确认该策略组名称与 BoxJS 中填写的是一致的

**Comment by Mosney** [comment]
感谢回复，确实是我这边的问题，我直接引用Netflix的远程规则集指定了`force-policy`，所以不存在上图中`Netflix`这个Policy。
由于之前用过的BoxJS脚本都会在这里显示所有出当前变量值就没往别的地方想，误以为是变量没有正确保存。
