### ISSUE TITLE
Netflix策略切换失效

### ISSUE THREAD

**Issue by spirytuslove** [Hyseen/Scripts#5]
圈叉自建的奈飞策略组设置的图标是绿色的 图标背景改成其他颜色以后 策略组切换就失效 只能识别自建策略组里面在用的节点 其他节点不检测

**Comment by spirytuslove** [comment]
发现第一次成功  之后图标颜色不换也会失效 只能识别出一个节点 其他节点不检测
![Uploading 2B4661DA-B312-49F9-A7CD-F3A69750F294.png…]()

**Comment by Hyseen** [comment]
请确认
1. 开启规则分流模式
2. 策略组及嵌套的子策略均为 static 类型

@spirytuslove

**Comment by spirytuslove** [comment]
我现在的分流模式是规则分流  Netflix策略组不是static的  但是字策略是static的  现在我把奈飞策略组删掉就留一个子策略的Netflix组  规则切换还是只有一个节点
