### ISSUE TITLE
“没有可用策略，请先运行…”，但解锁检测没有结果

### ISSUE THREAD

**Issue by Mosney** [Hyseen/Scripts#7]
策略组检测结果：
没有可用策略，请先运行 「Netflix 解锁检测」脚本
但是运行检测脚本又没有输出结果

![EE29A624-3589-4760-A798-B2312F56F5B2](https://user-images.githubusercontent.com/22477230/152265749-6283d13f-4dd8-4fc1-9b95-8bfc317a98c8.jpeg)

![99F26146-FC15-42D1-8654-BE95CADBA78B](https://user-images.githubusercontent.com/22477230/152265755-c4b742e9-7b8e-4df0-b6c7-afac22ae4859.jpeg)

**Comment by Hyseen** [comment]
仅支持 static 类型的嵌套策略组

**Comment by Mosney** [comment]
知道了谢谢，要是脚本有错误提示就好了
